name: mavka
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^0.3.2
  carousel_slider: ^2.0.0
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.0.5
  flutter_spinkit: ^4.1.2+1
  google_sign_in: ^4.0.4
  firebase_storage: ^3.1.5
  flutter_rounded_progress_bar: 0.1.1
  flutter_facebook_login: ^1.1.1
  fluttertoast: ^4.0.0

  pedantic: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter


#todo png -> svg для іконок (а ще краще лібку з pub.dev, наприклад https://pub.dev/packages/material_design_icons_flutter)
flutter:
  assets:
    - assets/onboarding0.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/sign_up_pic/sign_up_inform.png
    - assets/sign_up_pic/sign_up_backpack.png
    - assets/sign_up_pic/sign_up_last.png
    - assets/sign_up_pic/sign_up_microbe.png
    - assets/sign_up_pic/sign_up_rocket.png
    - assets/sign_up_pic/sign_up_tree.png
    - assets/Icons_home.png
    - assets/Icons_check.png
    - assets/Icons_lessons.png
    - assets/Icons_profile.png
    - assets/test1.gif
    - assets/test2.png
    - assets/background1.jpg
    - assets/background2.jpg

  uses-material-design: true


#todo шрифти через GoogleFonts (https://pub.dev/packages/google_fonts)
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: fonts/Gilroy-Regular.ttf
    - family: GilroyBold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/icons/SocialIcons.ttf